#!/usr/bin/env python3
"""
https://www.hackerrank.com/challenges/list-comprehensions/problem
"""

if __name__ == '__main__':
    x, y, z, n = (int(input()) for _ in range(4))
    print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])




"""
#My solution
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    li = []
    for i in range(x+1):
        for j in range(y+1):
            for k in range(z+1):
                if i+j+k != n:
                    li.append([i,j,k])   
                    
    print(li)


"""
